import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const sources = [
    {
      url: "https://export.arxiv.org/api/query?search_query=cat:cs.AI&max_results=10&sortBy=lastUpdatedDate&sortOrder=descending",
      type: "arxiv",
      title: "arXiv CS.AI latest",
      countryCode: "GLOBAL",
      primaryLanguage: "en",
    },
    {
      url: "https://export.arxiv.org/api/query?search_query=cat:physics.soc-ph&max_results=10&sortBy=lastUpdatedDate&sortOrder=descending",
      type: "arxiv",
      title: "arXiv Societal Physics",
      countryCode: "GLOBAL",
      primaryLanguage: "en",
    },
    {
      url: "https://feeds.npr.org/1001/rss.xml",
      type: "rss",
      title: "NPR News",
      countryCode: "US",
      primaryLanguage: "en",
    },
    {
      url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
      type: "rss",
      title: "NYTimes World",
      countryCode: "US",
      primaryLanguage: "en",
    },
    {
      url: "https://www.oecd.org/about/newsroom/feeds/pressreleases-en.xml",
      type: "rss",
      title: "OECD Press Releases",
      countryCode: "GLOBAL",
      primaryLanguage: "en",
    },
    {
      url: "https://www.imf.org/-/media/Files/News/Articles/IMFNewsRSS.ashx",
      type: "rss",
      title: "IMF News",
      countryCode: "GLOBAL",
      primaryLanguage: "en",
    },
    {
      url: "https://www.whitehouse.gov/briefing-room/feed/",
      type: "rss",
      title: "White House Briefing Room",
      countryCode: "US",
      primaryLanguage: "en",
    },
    {
      url: "https://ec.europa.eu/commission/presscorner/home/en/rss.xml",
      type: "rss",
      title: "European Commission Press",
      countryCode: "EU",
      primaryLanguage: "en",
    },
    {
      url: "https://www.un.org/press/en/rss/feed",
      type: "rss",
      title: "United Nations Press",
      countryCode: "UN",
      primaryLanguage: "en",
    },
    {
      url: "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=science",
      type: "rss",
      title: "Science Magazine",
      countryCode: "US",
      primaryLanguage: "en",
    },
    {
      url: "https://www.nature.com/nature/articles?type=news-and-views&format=rss",
      type: "rss",
      title: "Nature News & Views",
      countryCode: "GB",
      primaryLanguage: "en",
    },
    {
      url: "https://www.tagesschau.de/xml/rss2/",
      type: "rss",
      title: "Tagesschau Politik",
      countryCode: "DE",
      primaryLanguage: "de",
    },
    {
      url: "https://www3.nhk.or.jp/rss/news/cat0.xml",
      type: "rss",
      title: "NHK 総合ニュース",
      countryCode: "JP",
      primaryLanguage: "ja",
    },
    {
      url: "https://feeds.folha.uol.com.br/mundo/rss091.xml",
      type: "rss",
      title: "Folha de S.Paulo Mundo",
      countryCode: "BR",
      primaryLanguage: "pt",
    },
    {
      url: "https://www.lemonde.fr/rss/une.xml",
      type: "rss",
      title: "Le Monde Une",
      countryCode: "FR",
      primaryLanguage: "fr",
    },
    {
      url: "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf",
      type: "rss",
      title: "AllAfrica Latest",
      countryCode: "AF",
      primaryLanguage: "en",
    },
    {
      url: "https://english.kyodonews.net/rss/news",
      type: "rss",
      title: "Kyodo News English",
      countryCode: "JP",
      primaryLanguage: "en",
    },
  ];

  for (const source of sources) {
    await prisma.source.upsert({
      where: { url: source.url },
      update: {
        title: source.title,
        active: true,
        countryCode: source.countryCode,
        primaryLanguage: source.primaryLanguage,
      },
      create: source,
    });
  }

  const topics = [
    {
      slug: "ai-governance",
      label: "AI Governance",
      group: "innovation",
      subcategory: "technology-policy",
      tags: ["technology", "policy", "ai"],
      professional: true,
      defaultMode: "quen-3.4b-thinking",
    },
    {
      slug: "climate-policy",
      label: "Climate Policy",
      group: "science",
      subcategory: "climate",
      tags: ["climate", "policy"],
      professional: true,
      defaultMode: "quen-3.4b-thinking",
    },
    {
      slug: "public-health",
      label: "Public Health",
      group: "science",
      subcategory: "health",
      tags: ["health", "care"],
      defaultMode: "quen-3.4b",
    },
    {
      slug: "mental-health",
      label: "Mental Health",
      group: "science",
      subcategory: "health-mental",
      tags: ["health", "wellbeing"],
      defaultMode: "quen-2.5-thinking",
    },
    {
      slug: "medical-research",
      label: "Medical Research",
      group: "science",
      subcategory: "health-research",
      tags: ["research", "biotech"],
      professional: true,
      defaultMode: "quen-3.4b",
    },
    {
      slug: "nutrition-science",
      label: "Nutrition Science",
      group: "science",
      subcategory: "health-nutrition",
      tags: ["nutrition", "wellness"],
      defaultMode: "quen-3.4b",
    },
    {
      slug: "health-systems-policy",
      label: "Health Systems Policy",
      group: "science",
      subcategory: "health-systems",
      tags: ["policy", "care delivery"],
      professional: true,
      defaultMode: "quen-3.4b-thinking",
    },
    {
      slug: "space-exploration",
      label: "Space Exploration",
      group: "science",
      subcategory: "science-space",
      tags: ["space", "missions"],
      defaultMode: "quen-3.4b",
    },
    {
      slug: "global-economy",
      label: "Global Economy",
      group: "economy",
      subcategory: "economy",
      tags: ["markets", "trade"],
      professional: true,
      defaultMode: "quen-3.4b",
    },
    {
      slug: "creative-economy",
      label: "Creative Economy",
      group: "economy",
      subcategory: "creative",
      tags: ["design", "media"],
      professional: true,
      defaultMode: "quen-3.4b",
    },
    {
      slug: "democracy",
      label: "Democracy & Institutions",
      group: "society",
      subcategory: "civic",
      tags: ["civic", "governance"],
      defaultMode: "quen-3.4b",
    },
    {
      slug: "security",
      label: "Security & Defense",
      group: "global",
      subcategory: "world",
      tags: ["security", "defense"],
      professional: true,
      defaultMode: "quen-3.4b",
    },
    {
      slug: "tech-ethics",
      label: "Tech Ethics",
      group: "innovation",
      subcategory: "technology-open",
      tags: ["ethics", "open source"],
      defaultMode: "quen-3.4b-thinking",
    },
    {
      slug: "hardware-manufacturing",
      label: "Hardware Supply Chains",
      group: "innovation",
      subcategory: "technology-hardware",
      tags: ["hardware", "supply chain"],
      professional: true,
      defaultMode: "quen-3.4b",
    },
    {
      slug: "education-innovation",
      label: "Education Innovation",
      group: "society",
      subcategory: "education",
      tags: ["education", "learning"],
      defaultMode: "quen-2.5",
    },
    {
      slug: "energy-systems",
      label: "Energy Systems",
      group: "science",
      subcategory: "science-energy",
      tags: ["energy", "grid"],
      professional: true,
      defaultMode: "quen-3.4b-thinking",
    },
    {
      slug: "biodiversity",
      label: "Biodiversity",
      group: "science",
      subcategory: "climate",
      tags: ["nature", "conservation"],
      defaultMode: "quen-3.4b",
    },
    {
      slug: "geopolitics",
      label: "Geopolitics",
      group: "global",
      subcategory: "world",
      tags: ["diplomacy", "conflict"],
      professional: true,
      defaultMode: "quen-3.4b-thinking",
    },
    {
      slug: "governance-eu",
      label: "European Union",
      group: "global",
      subcategory: "world-europe",
      tags: ["eu", "policy"],
      defaultMode: "quen-3.4b",
    },
    {
      slug: "us-policy",
      label: "United States Policy",
      group: "global",
      subcategory: "world-americas",
      tags: ["us", "policy"],
      defaultMode: "quen-3.4b",
    },
    {
      slug: "asia-pacific",
      label: "Asia-Pacific",
      group: "global",
      subcategory: "world-asia",
      tags: ["asia", "trade"],
      defaultMode: "quen-3.4b",
    },
    {
      slug: "africa-development",
      label: "Africa Development",
      group: "global",
      subcategory: "world-africa",
      tags: ["development", "governance"],
      defaultMode: "quen-3.4b",
    },
    {
      slug: "latin-america",
      label: "Latin America",
      group: "global",
      subcategory: "world-americas",
      tags: ["latam", "policy"],
      defaultMode: "quen-3.4b",
    },
    {
      slug: "finance",
      label: "Finance & Markets",
      group: "economy",
      subcategory: "economy",
      tags: ["finance", "markets"],
      professional: true,
      defaultMode: "quen-3.4b",
    },
    {
      slug: "innovation",
      label: "Innovation & Startups",
      group: "innovation",
      subcategory: "technology",
      tags: ["innovation", "startups"],
      defaultMode: "quen-3.4b",
    },
    {
      slug: "culture-language",
      label: "Languages & Words",
      group: "society",
      subcategory: "culture-language",
      tags: ["language", "culture"],
      defaultMode: "quen-2.5",
    },
    {
      slug: "words-rhetoric",
      label: "Words & Rhetoric",
      group: "society",
      subcategory: "culture-words",
      tags: ["rhetoric", "communication"],
      defaultMode: "quen-3.4b",
    },
    {
      slug: "justice-rights",
      label: "Justice & Rights",
      group: "society",
      subcategory: "justice",
      tags: ["rights", "law"],
      defaultMode: "quen-3.4b",
    },
    {
      slug: "media-literacy",
      label: "Media Literacy",
      group: "society",
      subcategory: "culture-media",
      tags: ["media", "verification"],
      professional: true,
      defaultMode: "quen-3.4b",
    },
    {
      slug: "lifelong-learning",
      label: "Lifelong Learning",
      group: "society",
      subcategory: "education-lifelong",
      tags: ["adult learning", "skills"],
      defaultMode: "quen-3.4b",
    },
    {
      slug: "solidarity-economy",
      label: "Solidarity Economy",
      group: "economy",
      subcategory: "economy-cooperatives",
      tags: ["co-ops", "community"],
      defaultMode: "quen-3.4b",
    },
  ];

  for (const topic of topics) {
    await prisma.topic.upsert({
      where: { slug: topic.slug },
      update: {
        label: topic.label,
        group: topic.group,
        subcategory: topic.subcategory,
        tags: topic.tags,
        professional: topic.professional ?? false,
        randomEligible: topic.randomEligible ?? true,
        defaultMode: topic.defaultMode ?? "quen-3.4b",
      },
      create: {
        slug: topic.slug,
        label: topic.label,
        group: topic.group,
        subcategory: topic.subcategory,
        tags: topic.tags,
        professional: topic.professional ?? false,
        randomEligible: topic.randomEligible ?? true,
        defaultMode: topic.defaultMode ?? "quen-3.4b",
      },
    });
  }
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
